/* BACK OFFICE ADVENTURE DX v14 - DISTINCT CHARACTER ART */
'use strict';
(function(){
  const P={
    Eugenio:['#56caff','#20384a','#f4f7f8','#1e2e38',26,18,31,'tie'],
    Farris:['#79dba2','#2a4c40','#edf7f1','#21362f',25.5,17,30,'badge'],
    Yurii:['#ffca67','#5a4729','#f7f1e4','#372d20',25,16.5,29,'zip'],
    Luca:['#c1a1ff','#463768','#f3eefb','#2a243b',26.5,17.5,30,'hood'],
    Tiziano:['#ff9a82','#465867','#f0f3f4','#26313d',26,18.5,31,'lead'],
    Daniele:['#79e0e8','#c8a533','#f3f5ed','#27343c',25.5,18,30,'safe'],
    Dalila:['#ff9bc4','#6e405d','#f8f2f6','#302836',25.5,16.5,28.5,'perm'],
    Giada:['#f5bd6d','#755837','#faf3e8','#352d26',25.5,16.5,28.5,'perm'],
    Michele:['#ffd34d','#1f2732','#f4f1e9','#171e26',27.5,19,32,'op']
  };
  const cfg=ch=>{const a=P[ch?.n]||['#66dfff','#32424c','#f4f6f7','#27343d',26,17.5,30,'tie'];return {accent:a[0],jacket:a[1],shirt:a[2],pants:a[3],head:a[4],tw:a[5],th:a[6],role:a[7],shoe:'#111820',skin:'#d39a78'};};
  const seg=(x1,y1,x2,y2,c,w)=>{ctx.save();ctx.strokeStyle=c;ctx.lineWidth=w;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.restore();};
  const dot=(x,y,r,c)=>{ctx.save();ctx.fillStyle=c;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.restore();};
  function face(im,x,y,r,b,t=0){ctx.save();ctx.translate(x,y);ctx.rotate(t);ctx.shadowColor='#000b';ctx.shadowBlur=10;ctx.fillStyle='#07111a';ctx.beginPath();ctx.arc(0,0,r+4,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.clip();if(im&&im.complete&&im.naturalWidth){const iw=im.naturalWidth,ih=im.naturalHeight,s=Math.min(iw,ih)*.78,sx=(iw-s)/2,sy=Math.max(0,Math.min(ih-s,(ih-s)*.19));ctx.drawImage(im,sx,sy,s,s,-r,-r,r*2,r*2);}else{ctx.fillStyle='#6e7d88';ctx.fillRect(-r,-r,r*2,r*2);}const g=ctx.createLinearGradient(-r,-r,r,r);g.addColorStop(0,'#ffffff26');g.addColorStop(.45,'#ffffff00');g.addColorStop(1,'#00000028');ctx.fillStyle=g;ctx.fillRect(-r,-r,r*2,r*2);ctx.restore();ctx.save();ctx.translate(x,y);ctx.rotate(t);ctx.strokeStyle='#061019';ctx.lineWidth=6;ctx.beginPath();ctx.arc(0,0,r+1.5,0,Math.PI*2);ctx.stroke();ctx.strokeStyle=b;ctx.lineWidth=2.4;ctx.beginPath();ctx.arc(0,0,r+.8,0,Math.PI*2);ctx.stroke();ctx.restore();}
  function chest(c){ctx.save();const a=c.accent;switch(c.role){case'tie':ctx.fillStyle=a;ctx.beginPath();ctx.moveTo(0,-2);ctx.lineTo(5,5);ctx.lineTo(1,21);ctx.lineTo(-4,5);ctx.closePath();ctx.fill();break;case'badge':ctx.strokeStyle=a;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-6,-2);ctx.lineTo(0,11);ctx.lineTo(6,-2);ctx.stroke();ctx.fillStyle='#eaf7f0';ctx.fillRect(-5,10,10,8);break;case'zip':ctx.strokeStyle=a;ctx.lineWidth=2.2;ctx.beginPath();ctx.moveTo(0,-7);ctx.lineTo(0,23);ctx.stroke();ctx.fillStyle=a;ctx.fillRect(-2,5,4,4);break;case'hood':ctx.strokeStyle=a;ctx.lineWidth=2.2;ctx.beginPath();ctx.arc(0,-5,12,.17*Math.PI,.83*Math.PI,true);ctx.stroke();break;case'lead':ctx.fillStyle=a;ctx.beginPath();ctx.moveTo(0,-1);ctx.lineTo(5,5);ctx.lineTo(1,21);ctx.lineTo(-4,5);ctx.closePath();ctx.fill();ctx.fillStyle='#f2ead0';ctx.fillRect(7,7,9,6);break;case'safe':ctx.fillStyle='#2d353b';ctx.fillRect(-4,-5,8,30);ctx.globalAlpha=.8;ctx.fillStyle='#f6dd61';ctx.fillRect(-14,5,28,4);ctx.fillRect(-14,15,28,4);break;case'perm':ctx.strokeStyle=a;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-13,-5);ctx.lineTo(-4,6);ctx.lineTo(-1,21);ctx.moveTo(13,-5);ctx.lineTo(4,6);ctx.lineTo(1,21);ctx.stroke();break;case'op':ctx.fillStyle=a;ctx.beginPath();ctx.moveTo(0,-2);ctx.lineTo(5,5);ctx.lineTo(1,22);ctx.lineTo(-4,5);ctx.closePath();ctx.fill();ctx.fillRect(-16,-7,7,4);ctx.fillRect(9,-7,7,4);ctx.globalAlpha=.4;ctx.strokeStyle=a;ctx.strokeRect(-19,-10,38,36);break;}ctx.restore();}
  drawPlayer=function(p,ch){if(!p||!ch)return;const t=performance.now(),c=cfg(ch),cx=p.x+p.w/2,f=p.facing||1,run=p.onGround&&Math.abs(p.vx)>55,air=!p.onGround,rise=air&&p.vy<0,dash=(game?.v7DashUntil||0)>t,hurt=p.hurt>0,ph=run?Math.sin((p.anim||0)*15.5):0,bob=run?Math.abs(Math.sin((p.anim||0)*15.5))*2.4:Math.sin(t/280)*1.1,lean=air?(rise?-0.09:0.1):Math.max(-.075,Math.min(.075,p.vx/3400));ctx.save();if(p.inv>0&&Math.floor(p.inv/80)%2===0)ctx.globalAlpha=.5;ctx.save();ctx.globalAlpha*=air?.14:.3;ctx.fillStyle='#000';ctx.beginPath();ctx.ellipse(cx,p.y+p.h+5,air?18:27,air?3.5:6,0,0,Math.PI*2);ctx.fill();ctx.restore();if(dash){for(let i=4;i>=1;i--){ctx.save();ctx.globalAlpha=.08*i;ctx.translate(-f*i*16,0);ctx.fillStyle=c.accent;ctx.beginPath();ctx.roundRect(cx-15,p.y+22,30,37,9);ctx.fill();ctx.restore();}}ctx.save();ctx.translate(cx,p.y+35+bob);ctx.rotate(lean);const tw=c.tw,th=c.th,step=run?ph*10:0;const lfx=air?(rise?-tw+1:-6):(-6-step),rfx=air?(rise?tw-1:tw+2):(6+step),lfy=air?(rise?35:42):42,rfy=air?(rise?23:34):42;seg(-6,18,lfx,lfy,c.pants,10);seg(6,18,rfx,rfy,c.pants,10);seg(lfx-7,lfy+1,lfx+6,lfy+1,c.shoe,5);seg(rfx-6,rfy+1,rfx+8,rfy+1,c.shoe,5);ctx.save();ctx.fillStyle=c.shirt;ctx.strokeStyle='#08131b';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-tw+2,-8);ctx.quadraticCurveTo(-tw-5,4,-tw+1,th-2);ctx.quadraticCurveTo(0,th+4,tw-1,th-2);ctx.quadraticCurveTo(tw+5,4,tw-2,-8);ctx.quadraticCurveTo(0,-14,-tw+2,-8);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();ctx.save();ctx.fillStyle=c.jacket;ctx.strokeStyle='#09131c';ctx.lineWidth=1.6;ctx.beginPath();ctx.moveTo(-tw+1,-6);ctx.lineTo(-5,-1);ctx.lineTo(-1,th-5);ctx.lineTo(-tw+3,th-5);ctx.quadraticCurveTo(-tw-2,7,-tw+1,-6);ctx.closePath();ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(tw-1,-6);ctx.lineTo(5,-1);ctx.lineTo(1,th-5);ctx.lineTo(tw-3,th-5);ctx.quadraticCurveTo(tw+2,7,tw-1,-6);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();chest(c);const ah=air?(rise?4:12):15,as=run?ph*8:0,lax=-15-c.tw/10-as,rax=15+c.tw/10+as;seg(-15,1,lax,ah,c.jacket,9);seg(15,1,rax,ah,c.jacket,9);dot(lax,ah,4.6,c.skin);dot(rax,ah,4.6,c.skin);ctx.restore();const hx=cx+f*(run?ph*1.2:0),hy=p.y+18+bob*.5+(rise?-1:(air?1:0));face(imgs?.[ch.n],hx,hy,c.head,c.accent,lean*.32);ctx.save();ctx.strokeStyle=c.shirt;ctx.lineWidth=4;ctx.beginPath();ctx.arc(hx,hy+24,8.5,.15*Math.PI,.85*Math.PI);ctx.stroke();ctx.restore();if(hurt){ctx.save();ctx.globalAlpha=.68;ctx.strokeStyle='#ff536d';ctx.lineWidth=3;ctx.beginPath();ctx.arc(cx,p.y+34,41+Math.sin(t/60)*2,0,Math.PI*2);ctx.stroke();ctx.restore();}if(game?.shield>0||game?.activeUntil>t){ctx.save();ctx.globalAlpha=.7;ctx.strokeStyle='#6cefff';ctx.lineWidth=3;ctx.setLineDash([7,4]);ctx.beginPath();ctx.arc(cx,p.y+p.h/2,41+Math.sin(t/100)*2,0,Math.PI*2);ctx.stroke();ctx.restore();}if(run&&!air){ctx.save();ctx.globalAlpha=.35;ctx.fillStyle='#d8e8ef';for(let i=0;i<3;i++){const dx=-f*(20+i*10);ctx.fillRect(cx+dx,p.y+p.h-2-(i%2)*3,5+i,2);}ctx.restore();}ctx.restore();};
  const oldRenderMenu=renderMenu;renderMenu=function(){oldRenderMenu();[...document.querySelectorAll('#roster .person')].forEach((card,i)=>{const ch=CH[i];if(!ch)return;const c=cfg(ch);card.classList.add('v14Person');card.style.setProperty('--char-accent',c.accent);card.style.setProperty('--char-jacket',c.jacket);card.style.setProperty('--char-shirt',c.shirt);card.querySelectorAll('.v13MiniBody,.v13Class').forEach(e=>e.remove());const av=card.querySelector('.avatar');let wrap=card.querySelector('.v14AvatarWrap')||card.querySelector('.v13AvatarWrap');if(av){if(!wrap){wrap=document.createElement('span');wrap.className='v14AvatarWrap';av.parentNode.insertBefore(wrap,av);wrap.appendChild(av);}wrap.classList.remove('v13AvatarWrap');wrap.classList.add('v14AvatarWrap');if(av.parentElement!==wrap)wrap.appendChild(av);if(!wrap.querySelector('.v14MiniBody'))wrap.insertAdjacentHTML('beforeend','<span class="v14MiniBody"></span><span class="v14MiniDetail"></span>');}const pn=card.querySelector('.pn');if(pn&&!pn.querySelector('.v14Class'))pn.insertAdjacentHTML('beforeend',`<span class="v14Class">${ch.op?'OP':'PLAY'}</span>`);const pd=card.querySelector('.pd');if(pd&&!card.querySelector('.v14Flavor'))pd.insertAdjacentHTML('afterend',`<div class="v14Flavor">${ch.op?'Unità speciale da fine livello':'Operatore specializzato'}</div>`);});};
  const s=document.createElement('style');s.textContent=`body.v14Characters #roster .person.v14Person{position:relative;overflow:hidden;padding-top:14px;border:1px solid color-mix(in srgb,var(--char-accent) 42%,#2a4256);background:radial-gradient(circle at 88% 15%,color-mix(in srgb,var(--char-accent) 16%,transparent),transparent 33%),linear-gradient(135deg,#0d1a24,#0a1520 55%,color-mix(in srgb,var(--char-accent) 7%,#09141d));box-shadow:inset 0 1px #ffffff0e,0 8px 22px #0003}.v14Person:before{content:'';position:absolute;left:0;top:0;bottom:0;width:4px;background:var(--char-accent);box-shadow:0 0 14px var(--char-accent)}.v14AvatarWrap{position:relative;display:block;flex:0 0 76px;width:76px;height:92px;align-self:center;margin-right:4px}.v14AvatarWrap .avatar{position:absolute;z-index:3;left:15px;top:1px;width:46px!important;height:46px!important;border-radius:50%!important;object-fit:cover;border:3px solid var(--char-accent)!important;box-shadow:0 0 0 4px #07111a,0 5px 12px #0008}.v14MiniBody{position:absolute;z-index:1;left:17px;top:43px;width:40px;height:36px;border-radius:12px 12px 8px 8px;background:linear-gradient(90deg,var(--char-jacket) 0 24%,var(--char-shirt) 24% 76%,var(--char-jacket) 76%);border:3px solid #07111a}.v14MiniBody:before{content:'';position:absolute;left:15px;top:-7px;width:10px;height:10px;border-radius:50%;background:#d39a78;border:2px solid #07111a}.v14MiniBody:after{content:'';position:absolute;left:16px;top:4px;width:6px;height:24px;background:var(--char-accent);clip-path:polygon(50% 0,100% 18%,68% 100%,32% 100%,0 18%)}.v14MiniDetail{position:absolute;z-index:2;left:10px;top:76px;width:54px;height:3px;background:linear-gradient(90deg,transparent,var(--char-accent),transparent);opacity:.8}.v14Class{display:inline-block;margin-left:7px;padding:2px 5px;border-radius:6px;background:color-mix(in srgb,var(--char-accent) 18%,#102331);color:var(--char-accent);border:1px solid color-mix(in srgb,var(--char-accent) 46%,#19303f);font-size:7px;letter-spacing:.08em;vertical-align:2px}.v14Flavor{margin-top:5px;font-size:10px;color:#b7cbd8;opacity:.88}`;document.head.appendChild(s);
  document.body.classList.add('v14Characters');document.title='Back Office Adventure DX v14';const lg=document.querySelector('.header .logo span');if(lg)lg.textContent='ADVENTURE DX v14';const sub=document.querySelector('.header .sub');if(sub)sub.textContent='Character Art v14: silhouette distinte, outfit unici, pose migliori e select screen più da videogioco.';try{renderMenu();}catch(e){console.warn('v14',e);}
})();