/* BACK OFFICE ADVENTURE DX v17 - COMPLETE CAST / 9 HEROES / 54 STATES */
'use strict';
(function(){
  const LOOK={
    Eugenio:['#56caff','#20394b','#f3f7f8','#1b2b37','◆'],Farris:['#79dba2','#294b40','#edf7f1','#20362f','▦'],Yurii:['#ffca67','#5a4728','#f7f2e5','#362d20','➤'],Luca:['#c1a1ff','#47386a','#f2eefb','#29243c','↑'],Tiziano:['#ff9a82','#455868','#f1f3f4','#26333d','★'],Daniele:['#79e0e8','#bfa02d','#f2f4ed','#29363e','✚'],Dalila:['#ff9bc4','#70435f','#faf3f7','#312a36','✓'],Giada:['#f5bd6d','#755936','#fbf4e9','#352e26','✦'],Michele:['#ffd34d','#202a35','#f4f1e9','#161e27','♛']
  };
  const POSES=['ATTESA','CORSA','SALTO','CADUTA','COLPO','ABILITÀ'];
  const lore={Eugenio:'Operatore versatile: attraversa ogni reparto e risolve le pratiche fuori competenza.',Farris:'Specialista dei dati: precisione, ritmo e chiusure multiple.',Yurii:'Il più rapido del gruppo: usa lo slancio per superare il caos.',Luca:'Specialista verticale: raggiunge piattaforme e documenti impossibili.',Tiziano:'Riferimento operativo: protegge la squadra quando la pressione sale.',Daniele:'Presidio sicurezza: trasforma l’area di lavoro in una zona protetta.',Dalila:'Specialista autorizzazioni: nessun permesso resta fermo troppo a lungo.',Giada:'Supporto affidabile: entra in campo con una protezione extra.',Michele:'Unità OP: velocità, potenza e autorità da responsabile Back Office.'};
  const styles=(ch)=>{const o=LOOK[ch.n]||LOOK.Eugenio;return `--v17-accent:${o[0]};--v17-jacket:${o[1]};--v17-shirt:${o[2]};--v17-pants:${o[3]}`};
  function figure(ch){const o=LOOK[ch.n]||LOOK.Eugenio;return `<div class="v17-figure" style="${styles(ch)}"><span class="v17-leg l"></span><span class="v17-leg r"></span><span class="v17-arm l"></span><span class="v17-arm r"></span><span class="v17-neck"></span><span class="v17-body"></span><img class="v17-head" alt="${ch.n}" src="${FACE_DATA[ch.n]}"><span class="v17-rolemark">${o[4]}</span></div>`}
  function ensureShowcase(){let box=document.querySelector('.v17-showcase');if(box)return box;const roster=document.querySelector('#roster');if(!roster)return null;box=document.createElement('div');box.className='v17-showcase';roster.parentNode.insertBefore(box,roster);return box;}
  function show(ch,idx){const box=ensureShowcase();if(!box)return;box.style.cssText=styles(ch);box.innerHTML=`<div class="v17-stage">${figure(ch)}</div><div class="v17-info"><div class="v17-kicker">OPERATORE ${String(idx+1).padStart(2,'0')} / 09</div><div class="v17-name">${ch.n}</div><div class="v17-role">${ch.role}</div><div class="v17-ability">X · ${ch.ability}</div><div class="v17-desc">${lore[ch.n]}</div></div><div class="v17-poses"><b>SET ANIMAZIONI</b>${POSES.map((p,i)=>`<span class="v17-pose ${i===0?'active':''}">${String(i+1).padStart(2,'0')} · ${p}</span>`).join('')}</div>`;let n=0;clearInterval(box._poseTimer);box._poseTimer=setInterval(()=>{if(!box.isConnected)return clearInterval(box._poseTimer);const ps=box.querySelectorAll('.v17-pose');ps.forEach(x=>x.classList.remove('active'));ps[n++%ps.length]?.classList.add('active');},850);}
  const priorMenu=renderMenu;
  renderMenu=function(){priorMenu();const cards=[...document.querySelectorAll('#roster .person')];cards.forEach((card,i)=>{const ch=CH[i];if(!ch)return;card.dataset.hero=ch.n;card.querySelector('.v17-state')?.remove();card.insertAdjacentHTML('afterbegin','<span class="v17-state">6 POSE</span>');card.addEventListener('mouseenter',()=>show(ch,i));card.addEventListener('focus',()=>show(ch,i));card.addEventListener('click',()=>show(ch,i));});const preferred=selectedChar>=0?selectedChar:0;show(CH[preferred],preferred);};
  const priorPlayer=drawPlayer;
  drawPlayer=function(p,ch){priorPlayer(p,ch);if(!p||!ch)return;const o=LOOK[ch.n]||LOOK.Eugenio,x=p.x+p.w/2,y=p.y+36,t=performance.now(),ability=(game?.v121AbilityUntil||0)>t;ctx.save();ctx.translate(x,y);ctx.strokeStyle=o[0];ctx.fillStyle='#07131de6';ctx.lineWidth=2;
    if(ch.n==='Daniele'){ctx.beginPath();ctx.arc(0,-23,18,Math.PI,0);ctx.lineTo(18,-19);ctx.lineTo(-18,-19);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#f4d64f';ctx.fillRect(-13,-23,26,4);}
    if(ch.n==='Dalila'||ch.n==='Giada'){ctx.rotate(-.08);ctx.fillStyle='#f8f1df';ctx.strokeRect(18,-2,13,18);ctx.fillRect(18,-2,13,18);ctx.strokeStyle=o[0];ctx.beginPath();ctx.moveTo(21,3);ctx.lineTo(28,3);ctx.moveTo(21,7);ctx.lineTo(28,7);ctx.stroke();}
    if(ch.n==='Farris'){ctx.fillStyle=o[0];ctx.fillRect(-4,-2,8,5);ctx.strokeRect(-4,-2,8,5);}
    if(ch.n==='Tiziano'){ctx.fillStyle=o[0];ctx.beginPath();ctx.moveTo(-20,-7);ctx.lineTo(-14,-12);ctx.lineTo(-8,-7);ctx.lineTo(-14,-2);ctx.closePath();ctx.fill();}
    if(ch.n==='Yurii'&&Math.abs(p.vx)>40){ctx.globalAlpha=.65;ctx.beginPath();ctx.moveTo(-p.facing*27,7);ctx.lineTo(-p.facing*43,1);ctx.lineTo(-p.facing*36,12);ctx.closePath();ctx.fill();}
    if(ch.n==='Luca'&&!p.onGround){ctx.globalAlpha=.7;ctx.beginPath();ctx.arc(0,25,26,0,Math.PI*2);ctx.stroke();}
    if(ch.n==='Michele'){ctx.fillStyle=o[0];ctx.beginPath();ctx.moveTo(-11,-27);ctx.lineTo(-6,-36);ctx.lineTo(0,-29);ctx.lineTo(6,-36);ctx.lineTo(11,-27);ctx.closePath();ctx.fill();ctx.stroke();}
    if(ch.n==='Eugenio'){ctx.fillStyle=o[0];ctx.beginPath();ctx.moveTo(17,-4);ctx.lineTo(25,2);ctx.lineTo(17,8);ctx.lineTo(9,2);ctx.closePath();ctx.fill();}
    if(ability){ctx.globalAlpha=.8;ctx.font='900 9px ui-monospace,monospace';ctx.textAlign='center';ctx.fillStyle=o[0];ctx.fillText(ch.ability,0,-48);}ctx.restore();};
  document.body.classList.add('v17Characters');document.title='Back Office Adventure DX v17';const logo=document.querySelector('.header .logo span');if(logo)logo.textContent='ADVENTURE DX v17';const sub=document.querySelector('.header .sub');if(sub)sub.textContent='Complete Cast: 9 personaggi autentici, 54 pose, outfit e accessori dedicati.';const credits=document.querySelector('#credits h2');if(credits)credits.textContent='BACK OFFICE ADVENTURE DX v17';try{renderMenu();}catch(e){console.warn('v17 complete cast',e);}
})();
